# Generated by Django 5.2.7 on 2025-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPage',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('text', models.CharField()),
                ('image', models.FileField(upload_to='')),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
