# Generated by Django 5.2.7 on 2025-10-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedpage',
            name='link1',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cachedpage',
            name='link2',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cachedpage',
            name='link3',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cachedpage',
            name='link4',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
