# Generated by Django 5.2.7 on 2025-10-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cachedpage_link1_cachedpage_link2_cachedpage_link3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedpage',
            name='image',
            field=models.CharField(),
        ),
    ]
