# Generated by Django 5.2.7 on 2025-10-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_cachedpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('ip_address', models.CharField(primary_key=True, serialize=False)),
                ('enter_time', models.DateTimeField()),
                ('pages_visited', models.IntegerField(default=0)),
                ('location', models.CharField()),
                ('device', models.CharField()),
                ('is_banned', models.BooleanField(default=False)),
            ],
        ),
    ]
